INSERT INTO MPA_RATINGS(RATING_NAME, RATING_DESCRIPTION) VALUES ('G', 'Film has no restrictions');
INSERT INTO MPA_RATINGS(RATING_NAME, RATING_DESCRIPTION) VALUES ('PG', 'Children are recommended to watch with parents');
INSERT INTO MPA_RATINGS(RATING_NAME, RATING_DESCRIPTION) VALUES ('PG-13', 'Watching without parents is strongly not recommended for children up to 13');
INSERT INTO MPA_RATINGS(RATING_NAME, RATING_DESCRIPTION) VALUES ('R', 'People under 17 are not allowed whithout parents');
INSERT INTO MPA_RATINGS(RATING_NAME, RATING_DESCRIPTION) VALUES ('NC-17', 'Forbidden for people under 17');

INSERT INTO GENRES(GENRE_NAME) VALUES ('Комедия');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Драма');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Мультфильм');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Триллер');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Документальный');
INSERT INTO GENRES(GENRE_NAME) VALUES ('Боевик');